### ISSUE TITLE
An error occurring while running the AutoCasC.py script in Python=3.8

### ISSUE THREAD

**Issue by AppWick-hub** [JohannKaspar/AutoCaSc#4]
Hi, 
I want to use AutoCasC. However, while implementing it, I got an error "ModuleNotFoundError: No module named 'tenacity'". I am using Python=3.8.15, tenacity=8.0.1, and pipenv=2022.12.19. While using the script, _AutoCaSc_core/AutoCaSc.py_, the package tenacity can't be imported for some reason, even though I have installed it multiple times. I have tried the same for python=3.9, 3.10, and 3.7, but the outcome is the same. Can you please help me to fix the issue?

Thanks

Apurba

**Comment by JohannKaspar** [comment]
Hi Apurba,
are you trying to use it in an IDE like PyCharm? Have you correctly set the interpreter to use the pipenv virtual environment?
Best
Johann

**Comment by AppWick-hub** [comment]
Hey Johann,
I actually didn't run the command _`pipenv install`_ after installing `pipenv.` So, now I can run the command.

Thanks

Apurba
